### ISSUE TITLE
Inconsistent behaviour of Object.getOwnPropertyDescriptor in Microsoft browsers

### ISSUE THREAD

**Issue by graforlock** [tornqvist/fun-component#1]
Should `fun-component` be using `function-name`  ? It doesn't work well (or at all) across all browsers (Edge, IE11).

The implementation seems to be dependant on `node` functionality, not really browser friendly, it doesn't respect and work with IE11 at all.

Issue reference: https://github.com/TooTallNate/node-function-name/issues/6

**Comment by graforlock** [comment]
Alternative: Anyone knows how to re-implement it without using `node-function-name` ?

**Comment by tornqvist** [comment]
Ohh, thanks for bringing this up! I wasn't aware of the lacking support in IE (though not surprised).

We could just lookup `render.name` and be rid of the `function-name` dependency. If name consistency is important we already do support explicitly supplying it `component('my-component', render)`.

**Comment by tornqvist** [comment]
Fixed in 3.1.0 🎉
