### ISSUE TITLE
Only one of multiple instances with the same arguments is rendered

### ISSUE THREAD

**Issue by diegolealco** [tornqvist/fun-component#5]
This might or might not be an issue, and it is a very edge case.

If I wanted to create multiple instances of a particular component with the same arguments, only the last instance in the DOM will be rendered. Consider the following:

```
const instance1 = myFunComponent({a:'a',b:'b'})
// ...
const instance2 = myFunComponent({a:'a',b:'b'})

return html`
<div>
  ${instance1}
  // ... some more markup,
  ${instance2}
</div>
`
```

In the above scenario, the second instance will be rendered, but not the first. A way around this would be to explicitly set an id, but I am confused as to whether this is the desired behaviour or not.

**Comment by diegolealco** [comment]
Looking around very briefly I noticed that the id and ncid are the same, which is generated here [choojs/nanocomponent:makeID](https://github.com/choojs/nanocomponent/blob/5f779a4b773239bbe41614110e0df1d767bb3cf3/index.js#L12), but I am really confused given that the ncid is generated using `Math.random()` which should yield unique ids to some extent, if I try to create 6 instances of the same component in a row, I will end up with 6 instances with the same ncid, but only 1 being rendered.

**Comment by tornqvist** [comment]
Your function `myFunComponent` will always point to one and the same instance of an element. For spawning several instances of the same component, try using the [`spawn`](https://github.com/tornqvist/fun-component/tree/master/spawn) plugin. It takes a function as an argument which is passed the render arguments and should return a unique string for that instance of the component.

Here I added a unique id to the two components render props which is then used by spawn to generate an id string.

```javascript
const spawn = require('fun-component/spawn')

myFunComponent.use(spawn((props) => `my-component-${props.id}`)

const instance1 = myFunComponent({a:'a', b:'b', id: 1})
const instance2 = myFunComponent({a:'a', b:'b', id: 2})

return html`
<div>
  ${instance1}
  // ... some more markup,
  ${instance2}
</div>
```

**Comment by diegolealco** [comment]
I see, it does work.

I am curious though, what's the reason behind making these components singletons as opposed to a function that generates a new instance? (without spawn). Sorry fro my ingorance.

Thanks

**Comment by tornqvist** [comment]
It's due to how the underlying [nanocomponent](https://github.com/choojs/nanocomponent) operates. To preserve a stateful instance of a component that updates in place it looks up the element in the DOM on render. If an instance of the element is found in the DOM it will morph the rendered DOM tree onto the existing one. So you can do things like this:

```javascript
var button = component(function button (ctx, clicks, onclick) {
  return html`
    <button onclick=${onclick}>
      Clicked ${clicks} times
    </button>
  `
})

var clicks = 0
function onclick () {
  clicks += 1
  button(clicks, onclick) // <- everytime this is called the button will update in place
}

document.body.appendChild(button(clicks, onclick))
```
